FROM ghcr.io/rocker-org/r-ver:4.3.1

# pak usually can install system deps, but JIC:
RUN apt-get update \
    && apt-get install -yqq --no-install-recommends \
    libcurl4-openssl-dev \
    gdal-bin libgdal-dev libgeos-dev \
    libicu-dev libnetcdf-dev libproj-dev \
    libssl-dev libudunits2-dev \
    && apt-get clean

RUN Rscript -e "install.packages('pak')"

COPY DESCRIPTION ./DESCRIPTION

RUN Rscript \
      # -e "options(repos = c(CRAN = 'https://p3m.dev/cran/__linux__/jammy/latest'))" \
      -e "pak::pak('dplyr')" \
      -e "pak::local_install_dev_deps()"

COPY ./ /appc/

RUN R CMD build appc

RUN R CMD INSTALL appc_*.tar.gz

RUN R CMD check --as-cran --no-manual --no-vignettes appc_*.tar.gz

RUN Rscript -e "library(appc)" -e "example(predict_pm25)"
