skip_if_offline()

test_that("get_daily_aqs() works", {
  aqs_pm <- get_daily_aqs("pm25", "2023")
  expect_equal(nrow(aqs_pm), 33283)
  expect_equal(names(aqs_pm), c("s2", "date", "pollutant", "conc"))
  expect_s3_class(aqs_pm, c("tbl_df", "tbl", "data.frame"))
  aqs_ozone <- get_daily_aqs("ozone", "2022")
  expect_equal(nrow(aqs_ozone), 364965)
  expect_equal(names(aqs_ozone), c("s2", "date", "pollutant", "conc"))
  expect_s3_class(aqs_ozone, c("tbl_df", "tbl", "data.frame"))
  aqs_no2 <- get_daily_aqs("ozone", "2021")
  expect_equal(nrow(aqs_no2), 373208)
  expect_equal(names(aqs_no2), c("s2", "date", "pollutant", "conc"))
  expect_s3_class(aqs_no2, c("tbl_df", "tbl", "data.frame"))
})
